db:
  image: kartoza/postgis
  hostname: db
  environment:
    - USERNAME=docker
    - PASS=docker

web:
  image: kartoza/osm-reporter
  hostname: web
  environment:
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGHOST=db
  ports:
    - "64000:8080"
  links:
    - db:db
  volumes:
    - ./reporter:/reporter

test:
  build: docker-test
  hostname: web
  environment:
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGHOST=db
  ports:
    - "64001:8080"
  links:
    - db:db
  volumes:
    - ./reporter:/reporter
