db:
  image: kartoza/postgis:9.4-2.1
  hostname: db
  container_name: osmreporter_db
  environment:
    - USERNAME=docker
    - PASS=docker

web:
  #image: kartoza/osm-reporter
  build: .
  dockerfile: Dockerfile
  hostname: web
  container_name: osmreporter_web
  environment:
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGHOST=db
  ports:
    - "64000:8080"
  links:
    - db:db
  volumes:
    - ./reporter:/reporter

dev:
  build: .
  dockerfile: Dockerfile.dev
  hostname: devweb
  container_name: osmreporter_devweb
  environment:
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGHOST=db
  ports:
    - "64002:5000"
  links:
    - db:db
  volumes:
    - ./reporter:/reporter

test:
  build: .
  dockerfile: Dockerfile.test
  hostname: testweb
  container_name: osmreporter_testweb
  environment:
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGHOST=db
  ports:
    - "64001:8080"
  links:
    - db:db
  volumes:
    - ./reporter:/reporter
